baseURL = "https://blog.orsinium.dev/"
languageCode = "en-us"
title = "Gram Publishing v2"
paginate = 40
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = false

[params]
env = "production"
keywords = ["blog", "golang", "python", "elixir", "rust", "security"]
# images = "["<link or path of image for opengraph, twitter-cards>"]"
DateFormat = "2006-02-01"
defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = true
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = true
showtoc = true
tocopen = false

[params.editPost]
URL = "https://github.com/orsinium/blog/content"
Text = "edit"
appendFilePath = true

[params.homeInfoParams]
Title = "Hi, I'm Gram ğŸ‘‹"
Content = "I write about ğŸ Python, ğŸƒ Go, ğŸ§ª Elixir, ğŸ¦€ Rust, and some other software stuff."

[[menu.main]]
identifier = "go"
name = "ğŸƒ go"
url = "/posts/go/"
weight = "1"

[[menu.main]]
identifier = "py"
name = "ğŸ py"
url = "/posts/py/"
weight = "2"

[[menu.main]]
identifier = "tags"
name = "ğŸ· tags"
url = "/tags/"
weight = "10"

[[menu.main]]
identifier = "author"
name = "ğŸ‘‹ author"
url = "https://orsinium.dev"
weight = "20"
