baseURL = "https://blog.orsinium.dev/"
languageCode = "en-us"
title = "Gram Publishing v2"
paginate = "5"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = false

[params]
env = "production # to enable google analytics, opengraph, twitter-cards and schema."
title = "Gram Publishing v2"
description = "ExampleSite description"
keywords = ["blog", "golang", "python", "elixir", "rust", "security"]
# images = "["<link or path of image for opengraph, twitter-cards>"]"
DateFormat = "2006-02-01"
defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = true
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = true
showtoc = true
tocopen = false

[params.editPost]
URL = "https://github.com/orsinium/blog/content"
Text = "edit"
appendFilePath = true

[params.homeInfoParams]
Title = "Hi, I'm Gram ğŸ‘‹"
Content = "I write about ğŸ Python, ğŸƒ Go, ğŸ§ª Elixir, ğŸ¦€ Rust, and some other software stuff"

[[menu.main]]
identifier = "golang"
name = "ğŸƒ golang"
url = "/tags/golang/"
weight = "1"

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = "10"

[[menu.main]]
identifier = "author"
name = "author"
url = "https://orsinium.dev"
weight = "20"
